//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlersOfCatan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettlersOfCatan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept or Decline.
        /// </summary>
        public static string EnglishAcceptFormTitle {
            get {
                return ResourceManager.GetString("EnglishAcceptFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Trade.
        /// </summary>
        public static string EnglishAcceptTradeButton {
            get {
                return ResourceManager.GetString("EnglishAcceptTradeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the Trade?.
        /// </summary>
        public static string EnglishAcceptTradePrompt {
            get {
                return ResourceManager.GetString("EnglishAcceptTradePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Rolled.
        /// </summary>
        public static string EnglishAlreadyRolled {
            get {
                return ResourceManager.GetString("EnglishAlreadyRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Not Chosen.
        /// </summary>
        public static string EnglishAmountNotChosen {
            get {
                return ResourceManager.GetString("EnglishAmountNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything.
        /// </summary>
        public static string EnglishAnything {
            get {
                return ResourceManager.GetString("EnglishAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string EnglishBack {
            get {
                return ResourceManager.GetString("EnglishBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your resources:.
        /// </summary>
        public static string EnglishBankPrompt {
            get {
                return ResourceManager.GetString("EnglishBankPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        public static string EnglishBrick {
            get {
                return ResourceManager.GetString("EnglishBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough brick..
        /// </summary>
        public static string EnglishBrickException {
            get {
                return ResourceManager.GetString("EnglishBrickException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Development Card.
        /// </summary>
        public static string EnglishBuyDevCard {
            get {
                return ResourceManager.GetString("EnglishBuyDevCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot build there..
        /// </summary>
        public static string EnglishCannotBuildThere {
            get {
                return ResourceManager.GetString("EnglishCannotBuildThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot roll in the first 2 rounds..
        /// </summary>
        public static string EnglishCannotRollFirstFew {
            get {
                return ResourceManager.GetString("EnglishCannotRollFirstFew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards.
        /// </summary>
        public static string EnglishCards {
            get {
                return ResourceManager.GetString("EnglishCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a number to remove for each resource..
        /// </summary>
        public static string EnglishChooseEachResource {
            get {
                return ResourceManager.GetString("EnglishChooseEachResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string EnglishClose {
            get {
                return ResourceManager.GetString("EnglishClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string EnglishCongratulations {
            get {
                return ResourceManager.GetString("EnglishCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Roll.
        /// </summary>
        public static string EnglishCurrentRoll {
            get {
                return ResourceManager.GetString("EnglishCurrentRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Trade.
        /// </summary>
        public static string EnglishDeclineTradeButton {
            get {
                return ResourceManager.GetString("EnglishDeclineTradeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Cards.
        /// </summary>
        public static string EnglishDevCards {
            get {
                return ResourceManager.GetString("EnglishDevCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click a hex to place the robber..
        /// </summary>
        public static string EnglishDoubleClick {
            get {
                return ResourceManager.GetString("EnglishDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        public static string EnglishEndTurn {
            get {
                return ResourceManager.GetString("EnglishEndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a Road and a Settlement now..
        /// </summary>
        public static string EnglishFirstFewPrompt {
            get {
                return ResourceManager.GetString("EnglishFirstFewPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Phase.
        /// </summary>
        public static string EnglishFirstFewTitle {
            get {
                return ResourceManager.GetString("EnglishFirstFewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Resources (TEST).
        /// </summary>
        public static string EnglishGenerateTest {
            get {
                return ResourceManager.GetString("EnglishGenerateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        public static string EnglishGrain {
            get {
                return ResourceManager.GetString("EnglishGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough grain..
        /// </summary>
        public static string EnglishGrainException {
            get {
                return ResourceManager.GetString("EnglishGrainException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since a 7 was rolled and you have .
        /// </summary>
        public static string EnglishInstructionLabel {
            get {
                return ResourceManager.GetString("EnglishInstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string EnglishInstructions {
            get {
                return ResourceManager.GetString("EnglishInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Resources.
        /// </summary>
        public static string EnglishInsufficientResources {
            get {
                return ResourceManager.GetString("EnglishInsufficientResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Room to Build.
        /// </summary>
        public static string EnglishInsufficientRoom {
            get {
                return ResourceManager.GetString("EnglishInsufficientRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid amount of brick..
        /// </summary>
        public static string EnglishInvalidBrick {
            get {
                return ResourceManager.GetString("EnglishInvalidBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid number of development cards..
        /// </summary>
        public static string EnglishInvalidDevCards {
            get {
                return ResourceManager.GetString("EnglishInvalidDevCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid amount of grain..
        /// </summary>
        public static string EnglishInvalidGrain {
            get {
                return ResourceManager.GetString("EnglishInvalidGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid amount of lumber..
        /// </summary>
        public static string EnglishInvalidLumber {
            get {
                return ResourceManager.GetString("EnglishInvalidLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid amount of ore..
        /// </summary>
        public static string EnglishInvalidOre {
            get {
                return ResourceManager.GetString("EnglishInvalidOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There would be an invalid amount of wool..
        /// </summary>
        public static string EnglishInvalidWool {
            get {
                return ResourceManager.GetString("EnglishInvalidWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any Knights to play..
        /// </summary>
        public static string EnglishKnightException {
            get {
                return ResourceManager.GetString("EnglishKnightException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knights.
        /// </summary>
        public static string EnglishKnights {
            get {
                return ResourceManager.GetString("EnglishKnights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumber.
        /// </summary>
        public static string EnglishLumber {
            get {
                return ResourceManager.GetString("EnglishLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough lumber..
        /// </summary>
        public static string EnglishLumberException {
            get {
                return ResourceManager.GetString("EnglishLumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlers of Catan - Main Menu.
        /// </summary>
        public static string EnglishMainMenuTitlebar {
            get {
                return ResourceManager.GetString("EnglishMainMenuTitlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player&apos;s cards are such that trade cannot be performed..
        /// </summary>
        public static string EnglishMakeTradeException {
            get {
                return ResourceManager.GetString("EnglishMakeTradeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string EnglishMaterials {
            get {
                return ResourceManager.GetString("EnglishMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopoly.
        /// </summary>
        public static string EnglishMonopoly {
            get {
                return ResourceManager.GetString("EnglishMonopoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any Monopoly cards to play..
        /// </summary>
        public static string EnglishMonopolyException {
            get {
                return ResourceManager.GetString("EnglishMonopolyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the resource you wish to monopolize.
        /// </summary>
        public static string EnglishMonopolyLabel {
            get {
                return ResourceManager.GetString("EnglishMonopolyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose one of the choices to steal from..
        /// </summary>
        public static string EnglishMustChoosePlayer {
            get {
                return ResourceManager.GetString("EnglishMustChoosePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough resources to build a city..
        /// </summary>
        public static string EnglishNeedCityResources {
            get {
                return ResourceManager.GetString("EnglishNeedCityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough resources to build a road..
        /// </summary>
        public static string EnglishNeedRoadResources {
            get {
                return ResourceManager.GetString("EnglishNeedRoadResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough resources to build a settlement..
        /// </summary>
        public static string EnglishNeedSettlementResources {
            get {
                return ResourceManager.GetString("EnglishNeedSettlementResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player cannot have negative brick..
        /// </summary>
        public static string EnglishNegativeBrick {
            get {
                return ResourceManager.GetString("EnglishNegativeBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player cannot have negative grain..
        /// </summary>
        public static string EnglishNegativeGrain {
            get {
                return ResourceManager.GetString("EnglishNegativeGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player cannot have negative lumber..
        /// </summary>
        public static string EnglishNegativeLumber {
            get {
                return ResourceManager.GetString("EnglishNegativeLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player cannot have negative ore..
        /// </summary>
        public static string EnglishNegativeOre {
            get {
                return ResourceManager.GetString("EnglishNegativeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player cannot have negative wool..
        /// </summary>
        public static string EnglishNegativeWool {
            get {
                return ResourceManager.GetString("EnglishNegativeWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string EnglishNewGame {
            get {
                return ResourceManager.GetString("EnglishNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        public static string EnglishNobody {
            get {
                return ResourceManager.GetString("EnglishNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Owner.
        /// </summary>
        public static string EnglishNotOwner {
            get {
                return ResourceManager.GetString("EnglishNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Computers.
        /// </summary>
        public static string EnglishNumComps {
            get {
                return ResourceManager.GetString("EnglishNumComps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Players.
        /// </summary>
        public static string EnglishNumPlayers {
            get {
                return ResourceManager.GetString("EnglishNumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot roll more than once per turn..
        /// </summary>
        public static string EnglishOnlyOneRoll {
            get {
                return ResourceManager.GetString("EnglishOnlyOneRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        public static string EnglishOre {
            get {
                return ResourceManager.GetString("EnglishOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough ore..
        /// </summary>
        public static string EnglishOreException {
            get {
                return ResourceManager.GetString("EnglishOreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Someone.
        /// </summary>
        public static string EnglishPickSomeone {
            get {
                return ResourceManager.GetString("EnglishPickSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your two resources.
        /// </summary>
        public static string EnglishPickTwoResources {
            get {
                return ResourceManager.GetString("EnglishPickTwoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place two roads now..
        /// </summary>
        public static string EnglishPlaceRoads {
            get {
                return ResourceManager.GetString("EnglishPlaceRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string EnglishPlayers {
            get {
                return ResourceManager.GetString("EnglishPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string EnglishPoints {
            get {
                return ResourceManager.GetString("EnglishPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose Trade.
        /// </summary>
        public static string EnglishProposeTrade {
            get {
                return ResourceManager.GetString("EnglishProposeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string EnglishRemove {
            get {
                return ResourceManager.GetString("EnglishRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Amount.
        /// </summary>
        public static string EnglishRemoveAmount {
            get {
                return ResourceManager.GetString("EnglishRemoveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Your Cards.
        /// </summary>
        public static string EnglishRemoveCardsTitle {
            get {
                return ResourceManager.GetString("EnglishRemoveCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must remove .
        /// </summary>
        public static string EnglishRemoveInstructionLabel {
            get {
                return ResourceManager.GetString("EnglishRemoveInstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string EnglishResource {
            get {
                return ResourceManager.GetString("EnglishResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource to Gain.
        /// </summary>
        public static string EnglishResourceGain {
            get {
                return ResourceManager.GetString("EnglishResourceGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource to Trade.
        /// </summary>
        public static string EnglishResourceTrade {
            get {
                return ResourceManager.GetString("EnglishResourceTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Builder.
        /// </summary>
        public static string EnglishRoadBuilder {
            get {
                return ResourceManager.GetString("EnglishRoadBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any Road Builder cards to play..
        /// </summary>
        public static string EnglishRoadBuilderException {
            get {
                return ResourceManager.GetString("EnglishRoadBuilderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board will repaint once you end your turn..
        /// </summary>
        public static string EnglishRobberNote {
            get {
                return ResourceManager.GetString("EnglishRobberNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can&apos;t be placed on the hex that it was just on..
        /// </summary>
        public static string EnglishRobberReminder {
            get {
                return ResourceManager.GetString("EnglishRobberReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLL!.
        /// </summary>
        public static string EnglishRoll {
            get {
                return ResourceManager.GetString("EnglishRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must roll before ending your turn..
        /// </summary>
        public static string EnglishRollBeforeEnd {
            get {
                return ResourceManager.GetString("EnglishRollBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll the Dice.
        /// </summary>
        public static string EnglishRollTheDice {
            get {
                return ResourceManager.GetString("EnglishRollTheDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string EnglishRounds {
            get {
                return ResourceManager.GetString("EnglishRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string EnglishRules {
            get {
                return ResourceManager.GetString("EnglishRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That settlement does not belong to you..
        /// </summary>
        public static string EnglishSettlementNotBelong {
            get {
                return ResourceManager.GetString("EnglishSettlementNotBelong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string EnglishSomethingWrong {
            get {
                return ResourceManager.GetString("EnglishSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string EnglishStart {
            get {
                return ResourceManager.GetString("EnglishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal.
        /// </summary>
        public static string EnglishSteal {
            get {
                return ResourceManager.GetString("EnglishSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick who to steal from.
        /// </summary>
        public static string EnglishStealCardCombo {
            get {
                return ResourceManager.GetString("EnglishStealCardCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Card.
        /// </summary>
        public static string EnglishStealCardTitle {
            get {
                return ResourceManager.GetString("EnglishStealCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string EnglishSubmit {
            get {
                return ResourceManager.GetString("EnglishSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlers Of Catan.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Early to Roll.
        /// </summary>
        public static string EnglishTooEarlyToRoll {
            get {
                return ResourceManager.GetString("EnglishTooEarlyToRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade with Bank.
        /// </summary>
        public static string EnglishTradeWithBank {
            get {
                return ResourceManager.GetString("EnglishTradeWithBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the rest of your free roads/settlements before ending turn..
        /// </summary>
        public static string EnglishUnplacedStuffPrompt {
            get {
                return ResourceManager.GetString("EnglishUnplacedStuffPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplaced Roads/Settlements.
        /// </summary>
        public static string EnglishUnplacedStuffTitle {
            get {
                return ResourceManager.GetString("EnglishUnplacedStuffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory Point.
        /// </summary>
        public static string EnglishVictoryPoint {
            get {
                return ResourceManager.GetString("EnglishVictoryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any Victory Point cards to play..
        /// </summary>
        public static string EnglishVictoryPointException {
            get {
                return ResourceManager.GetString("EnglishVictoryPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINNER!.
        /// </summary>
        public static string EnglishWinner {
            get {
                return ResourceManager.GetString("EnglishWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wool.
        /// </summary>
        public static string EnglishWool {
            get {
                return ResourceManager.GetString("EnglishWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough wool..
        /// </summary>
        public static string EnglishWoolException {
            get {
                return ResourceManager.GetString("EnglishWoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Number of Cards Removed.
        /// </summary>
        public static string EnglishWrongNumberOfCards {
            get {
                return ResourceManager.GetString("EnglishWrongNumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your trade-in amounts add up to .
        /// </summary>
        public static string EnglishWrongTradeIn {
            get {
                return ResourceManager.GetString("EnglishWrongTradeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Plenty.
        /// </summary>
        public static string EnglishYearOfPlenty {
            get {
                return ResourceManager.GetString("EnglishYearOfPlenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any Year of Plenty cards to play..
        /// </summary>
        public static string EnglishYearOfPlentyException {
            get {
                return ResourceManager.GetString("EnglishYearOfPlentyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar o Rechazar.
        /// </summary>
        public static string SpanishAcceptFormTitle {
            get {
                return ResourceManager.GetString("SpanishAcceptFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Trade.
        /// </summary>
        public static string SpanishAcceptTradeButton {
            get {
                return ResourceManager.GetString("SpanishAcceptTradeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepte el Comercio?.
        /// </summary>
        public static string SpanishAcceptTradePrompt {
            get {
                return ResourceManager.GetString("SpanishAcceptTradePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya Laminado.
        /// </summary>
        public static string SpanishAlreadyRolled {
            get {
                return ResourceManager.GetString("SpanishAlreadyRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto No Elegido.
        /// </summary>
        public static string SpanishAmountNotChosen {
            get {
                return ResourceManager.GetString("SpanishAmountNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo.
        /// </summary>
        public static string SpanishAnything {
            get {
                return ResourceManager.GetString("SpanishAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retorno.
        /// </summary>
        public static string SpanishBack {
            get {
                return ResourceManager.GetString("SpanishBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir los Recursos:.
        /// </summary>
        public static string SpanishBankPrompt {
            get {
                return ResourceManager.GetString("SpanishBankPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladrillo.
        /// </summary>
        public static string SpanishBrick {
            get {
                return ResourceManager.GetString("SpanishBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficiente ladrillo..
        /// </summary>
        public static string SpanishBrickException {
            get {
                return ResourceManager.GetString("SpanishBrickException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar Tarjeta de Desarrollo.
        /// </summary>
        public static string SpanishBuyDevCard {
            get {
                return ResourceManager.GetString("SpanishBuyDevCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede construir allí..
        /// </summary>
        public static string SpanishCannotBuildThere {
            get {
                return ResourceManager.GetString("SpanishCannotBuildThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede rodar en las 2 primeras rondas..
        /// </summary>
        public static string SpanishCannotRollFirstFew {
            get {
                return ResourceManager.GetString("SpanishCannotRollFirstFew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tarjetas.
        /// </summary>
        public static string SpanishCards {
            get {
                return ResourceManager.GetString("SpanishCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted debe elegir un número de quitar para cada recurso..
        /// </summary>
        public static string SpanishChooseEachResource {
            get {
                return ResourceManager.GetString("SpanishChooseEachResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string SpanishClose {
            get {
                return ResourceManager.GetString("SpanishClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felicitaciones!.
        /// </summary>
        public static string SpanishCongratulations {
            get {
                return ResourceManager.GetString("SpanishCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollo Actual.
        /// </summary>
        public static string SpanishCurrentRoll {
            get {
                return ResourceManager.GetString("SpanishCurrentRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar Comercio.
        /// </summary>
        public static string SpanishDeclineTradeButton {
            get {
                return ResourceManager.GetString("SpanishDeclineTradeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas de Desarrollo.
        /// </summary>
        public static string SpanishDevCards {
            get {
                return ResourceManager.GetString("SpanishDevCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga doble clic en un hexágono para colocar el ladrón..
        /// </summary>
        public static string SpanishDoubleClick {
            get {
                return ResourceManager.GetString("SpanishDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro Final.
        /// </summary>
        public static string SpanishEndTurn {
            get {
                return ResourceManager.GetString("SpanishEndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloque una Carretera y una Solución ahora.
        /// </summary>
        public static string SpanishFirstFewPrompt {
            get {
                return ResourceManager.GetString("SpanishFirstFewPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase de Configuración.
        /// </summary>
        public static string SpanishFirstFewTitle {
            get {
                return ResourceManager.GetString("SpanishFirstFewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar Recursos (PRUEBA).
        /// </summary>
        public static string SpanishGenerateTest {
            get {
                return ResourceManager.GetString("SpanishGenerateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grano.
        /// </summary>
        public static string SpanishGrain {
            get {
                return ResourceManager.GetString("SpanishGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficiente grano..
        /// </summary>
        public static string SpanishGrainException {
            get {
                return ResourceManager.GetString("SpanishGrainException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto que un 7 fue enrollada y tiene .
        /// </summary>
        public static string SpanishInstructionLabel {
            get {
                return ResourceManager.GetString("SpanishInstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones.
        /// </summary>
        public static string SpanishInstructions {
            get {
                return ResourceManager.GetString("SpanishInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuficiencia de Recursos.
        /// </summary>
        public static string SpanishInsufficientResources {
            get {
                return ResourceManager.GetString("SpanishInsufficientResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio Suficiente para Construir.
        /// </summary>
        public static string SpanishInsufficientRoom {
            get {
                return ResourceManager.GetString("SpanishInsufficientRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No habría una cantidad no válida de ladrillo..
        /// </summary>
        public static string SpanishInvalidBrick {
            get {
                return ResourceManager.GetString("SpanishInvalidBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habría un número no válido de tarjetas de desarrollo..
        /// </summary>
        public static string SpanishInvalidDevCards {
            get {
                return ResourceManager.GetString("SpanishInvalidDevCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No habría una cantidad no válida de grano..
        /// </summary>
        public static string SpanishInvalidGrain {
            get {
                return ResourceManager.GetString("SpanishInvalidGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No habría una cantidad no válida de la madera de construcción..
        /// </summary>
        public static string SpanishInvalidLumber {
            get {
                return ResourceManager.GetString("SpanishInvalidLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No habría una cantidad no válida de mineral..
        /// </summary>
        public static string SpanishInvalidOre {
            get {
                return ResourceManager.GetString("SpanishInvalidOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No habría una cantidad no válida de lana..
        /// </summary>
        public static string SpanishInvalidWool {
            get {
                return ResourceManager.GetString("SpanishInvalidWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene ninguna carta Caballero para jugar..
        /// </summary>
        public static string SpanishKnightException {
            get {
                return ResourceManager.GetString("SpanishKnightException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caballeros.
        /// </summary>
        public static string SpanishKnights {
            get {
                return ResourceManager.GetString("SpanishKnights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maderas.
        /// </summary>
        public static string SpanishLumber {
            get {
                return ResourceManager.GetString("SpanishLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficiente madera..
        /// </summary>
        public static string SpanishLumberException {
            get {
                return ResourceManager.GetString("SpanishLumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonos de Catan - Menú Principal.
        /// </summary>
        public static string SpanishMainMenuTitlebar {
            get {
                return ResourceManager.GetString("SpanishMainMenuTitlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas de jugador son tales que el comercio no se puede realizar..
        /// </summary>
        public static string SpanishMakeTradeException {
            get {
                return ResourceManager.GetString("SpanishMakeTradeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales.
        /// </summary>
        public static string SpanishMaterials {
            get {
                return ResourceManager.GetString("SpanishMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopolio.
        /// </summary>
        public static string SpanishMonopoly {
            get {
                return ResourceManager.GetString("SpanishMonopoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene ninguna tarjeta de Monopoly para jugar..
        /// </summary>
        public static string SpanishMonopolyException {
            get {
                return ResourceManager.GetString("SpanishMonopolyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija el recurso que desea monopolizar.
        /// </summary>
        public static string SpanishMonopolyLabel {
            get {
                return ResourceManager.GetString("SpanishMonopolyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted debe elegir una de las opciones, que robasen..
        /// </summary>
        public static string SpanishMustChoosePlayer {
            get {
                return ResourceManager.GetString("SpanishMustChoosePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficientes recursos para construir una ciudad..
        /// </summary>
        public static string SpanishNeedCityResources {
            get {
                return ResourceManager.GetString("SpanishNeedCityResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficientes recursos para construir una carretera..
        /// </summary>
        public static string SpanishNeedRoadResources {
            get {
                return ResourceManager.GetString("SpanishNeedRoadResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficientes recursos para construir un asentamiento..
        /// </summary>
        public static string SpanishNeedSettlementResources {
            get {
                return ResourceManager.GetString("SpanishNeedSettlementResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador no puede tener ladrillo negativo..
        /// </summary>
        public static string SpanishNegativeBrick {
            get {
                return ResourceManager.GetString("SpanishNegativeBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador no puede tener grano negativo..
        /// </summary>
        public static string SpanishNegativeGrain {
            get {
                return ResourceManager.GetString("SpanishNegativeGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador no puede tener la madera negativo..
        /// </summary>
        public static string SpanishNegativeLumber {
            get {
                return ResourceManager.GetString("SpanishNegativeLumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador no puede tener el mineral negativo..
        /// </summary>
        public static string SpanishNegativeOre {
            get {
                return ResourceManager.GetString("SpanishNegativeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador no puede tener lana negativo..
        /// </summary>
        public static string SpanishNegativeWool {
            get {
                return ResourceManager.GetString("SpanishNegativeWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Juego.
        /// </summary>
        public static string SpanishNewGame {
            get {
                return ResourceManager.GetString("SpanishNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadie.
        /// </summary>
        public static string SpanishNobody {
            get {
                return ResourceManager.GetString("SpanishNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Propietario.
        /// </summary>
        public static string SpanishNotOwner {
            get {
                return ResourceManager.GetString("SpanishNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Equipos.
        /// </summary>
        public static string SpanishNumComps {
            get {
                return ResourceManager.GetString("SpanishNumComps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Jugadores.
        /// </summary>
        public static string SpanishNumPlayers {
            get {
                return ResourceManager.GetString("SpanishNumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede rodar más de una vez por turno..
        /// </summary>
        public static string SpanishOnlyOneRoll {
            get {
                return ResourceManager.GetString("SpanishOnlyOneRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral.
        /// </summary>
        public static string SpanishOre {
            get {
                return ResourceManager.GetString("SpanishOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficiente mineral..
        /// </summary>
        public static string SpanishOreException {
            get {
                return ResourceManager.GetString("SpanishOreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoger a Alguien.
        /// </summary>
        public static string SpanishPickSomeone {
            get {
                return ResourceManager.GetString("SpanishPickSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escoger sus dos recursos.
        /// </summary>
        public static string SpanishPickTwoResources {
            get {
                return ResourceManager.GetString("SpanishPickTwoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colocar dos caminos ahora..
        /// </summary>
        public static string SpanishPlaceRoads {
            get {
                return ResourceManager.GetString("SpanishPlaceRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string SpanishPlayers {
            get {
                return ResourceManager.GetString("SpanishPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos:.
        /// </summary>
        public static string SpanishPoints {
            get {
                return ResourceManager.GetString("SpanishPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proponer el Comercio.
        /// </summary>
        public static string SpanishProposeTrade {
            get {
                return ResourceManager.GetString("SpanishProposeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirar.
        /// </summary>
        public static string SpanishRemove {
            get {
                return ResourceManager.GetString("SpanishRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire Monto.
        /// </summary>
        public static string SpanishRemoveAmount {
            get {
                return ResourceManager.GetString("SpanishRemoveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire Sus Tarjetas.
        /// </summary>
        public static string SpanishRemoveCardsTitle {
            get {
                return ResourceManager.GetString("SpanishRemoveCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe quitar .
        /// </summary>
        public static string SpanishRemoveInstructionLabel {
            get {
                return ResourceManager.GetString("SpanishRemoveInstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso.
        /// </summary>
        public static string SpanishResource {
            get {
                return ResourceManager.GetString("SpanishResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos para Ganar.
        /// </summary>
        public static string SpanishResourceGain {
            get {
                return ResourceManager.GetString("SpanishResourceGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos para Comercio.
        /// </summary>
        public static string SpanishResourceTrade {
            get {
                return ResourceManager.GetString("SpanishResourceTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor de Carreteras.
        /// </summary>
        public static string SpanishRoadBuilder {
            get {
                return ResourceManager.GetString("SpanishRoadBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene ninguna tarjeta Constructor de Carreteras para jugar..
        /// </summary>
        public static string SpanishRoadBuilderException {
            get {
                return ResourceManager.GetString("SpanishRoadBuilderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La junta se volverá a dibujar una vez que termina su turno..
        /// </summary>
        public static string SpanishRobberNote {
            get {
                return ResourceManager.GetString("SpanishRobberNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede colocar en el hexágono que era sólo en..
        /// </summary>
        public static string SpanishRobberReminder {
            get {
                return ResourceManager.GetString("SpanishRobberReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLLO!.
        /// </summary>
        public static string SpanishRoll {
            get {
                return ResourceManager.GetString("SpanishRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe rodar antes de terminar su turno..
        /// </summary>
        public static string SpanishRollBeforeEnd {
            get {
                return ResourceManager.GetString("SpanishRollBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirar los Dados.
        /// </summary>
        public static string SpanishRollTheDice {
            get {
                return ResourceManager.GetString("SpanishRollTheDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rondas.
        /// </summary>
        public static string SpanishRounds {
            get {
                return ResourceManager.GetString("SpanishRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas.
        /// </summary>
        public static string SpanishRules {
            get {
                return ResourceManager.GetString("SpanishRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ese acuerdo no pertenece a usted..
        /// </summary>
        public static string SpanishSettlementNotBelong {
            get {
                return ResourceManager.GetString("SpanishSettlementNotBelong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal ....
        /// </summary>
        public static string SpanishSomethingWrong {
            get {
                return ResourceManager.GetString("SpanishSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar.
        /// </summary>
        public static string SpanishStart {
            get {
                return ResourceManager.GetString("SpanishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robar.
        /// </summary>
        public static string SpanishSteal {
            get {
                return ResourceManager.GetString("SpanishSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija a quién robar a.
        /// </summary>
        public static string SpanishStealCardCombo {
            get {
                return ResourceManager.GetString("SpanishStealCardCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tome una Tarjeta.
        /// </summary>
        public static string SpanishStealCardTitle {
            get {
                return ResourceManager.GetString("SpanishStealCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentar.
        /// </summary>
        public static string SpanishSubmit {
            get {
                return ResourceManager.GetString("SpanishSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonos de Catan.
        /// </summary>
        public static string SpanishTitle {
            get {
                return ResourceManager.GetString("SpanishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demasiado Temprano para Rollo.
        /// </summary>
        public static string SpanishTooEarlyToRoll {
            get {
                return ResourceManager.GetString("SpanishTooEarlyToRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio con el Banco.
        /// </summary>
        public static string SpanishTradeWithBank {
            get {
                return ResourceManager.GetString("SpanishTradeWithBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloque el resto de sus caminos libres / asentamientos antes de terminar su vez..
        /// </summary>
        public static string SpanishUnplacedStuffPrompt {
            get {
                return ResourceManager.GetString("SpanishUnplacedStuffPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminos no Posicionados / Asentamientos.
        /// </summary>
        public static string SpanishUnplacedStuffTitle {
            get {
                return ResourceManager.GetString("SpanishUnplacedStuffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Victoria.
        /// </summary>
        public static string SpanishVictoryPoint {
            get {
                return ResourceManager.GetString("SpanishVictoryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene ninguna carta de Puntos de Victoria para jugar..
        /// </summary>
        public static string SpanishVictoryPointException {
            get {
                return ResourceManager.GetString("SpanishVictoryPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GANADOR!.
        /// </summary>
        public static string SpanishWinner {
            get {
                return ResourceManager.GetString("SpanishWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lana.
        /// </summary>
        public static string SpanishWool {
            get {
                return ResourceManager.GetString("SpanishWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene suficiente lana..
        /// </summary>
        public static string SpanishWoolException {
            get {
                return ResourceManager.GetString("SpanishWoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Incorrecto de Cartas Eliminadas.
        /// </summary>
        public static string SpanishWrongNumberOfCards {
            get {
                return ResourceManager.GetString("SpanishWrongNumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asegúrese de que sus cantidades con el comercio en suman .
        /// </summary>
        public static string SpanishWrongTradeIn {
            get {
                return ResourceManager.GetString("SpanishWrongTradeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de la Abundancia.
        /// </summary>
        public static string SpanishYearOfPlenty {
            get {
                return ResourceManager.GetString("SpanishYearOfPlenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene ningún Año de Abundancia cartas para jugar..
        /// </summary>
        public static string SpanishYearOfPlentyException {
            get {
                return ResourceManager.GetString("SpanishYearOfPlentyException", resourceCulture);
            }
        }
    }
}
